let data = [
    {
        "condominio": "kitnet",
        "nome": "jão da roça",
        "empresa": "Leite da vaquinha",
        "profissao": "caminhoneiro",
        "produtos": ["bolos", "pudim", "pinga"],
        "whatsapp": 5511944751710,
        "facebook": "sdaksdjasdjjsdasjd.com.br/asdasd",
        "instagram": "sdaksdjasdjjsdasjd.com.br/asdasd",
        "bloco": 3,
        "apt": 202,
        "pagamento": ["dinheiro", "CEF", "BB", "Bradesco", "Santander", "Cartões", "NuBank"],
        "categoria": "Loja",
        "tags": ["alimentação", "bedidas"],
        "verificado": false,
        "assinante": false,
    },{
        "condominio": "nautilus",
        "nome": "Victor",
        "empresa": "Açai do Victor e Vini",
        "profissao": "",
        "produtos": ["Açai"],
        "whatsapp": 5584988599584,
        "facebook": "",
        "instagram": "",
        "bloco": 0,
        "apt": 0,
        "pagamento": ["dinheiro", "Cartões"],
        "categoria": "Restaurante",
        "tags": ["Alimentação", "Restaurantes", "Açai"],
        "verificado": true,
        "assinante": false,
    },{
        "condominio": "nautilus",
        "nome": "Aretusa Sousa",
        "empresa": "Alexandria Marmitaria",
        "profissao": "",
        "produtos": ["Marmitas"],
        "whatsapp": 5584998285032,
        "facebook": "",
        "instagram": "",
        "bloco": 2,
        "apt": 1102,
        "pagamento": ["dinheiro", "Cartões"],
        "categoria": "Serviços",
        "tags": ["Alimentação", "Restaurantes", "Marmitas"],
        "verificado": true,
        "assinante": false,
    },{
        "condominio": "nautilus",
        "nome": "Alcione",
        "empresa": "Alcione Sobremesas",
        "profissao": "",
        "produtos": ["Açai", "Dindin Gourmet"],
        "whatsapp": 5584988498469,
        "facebook": "",
        "instagram": "",
        "bloco": 0,
        "apt": 0,
        "pagamento": ["dinheiro", "Cartões"],
        "categoria": "Serviços",
        "tags": ["Alimentação", "Restaurantes", "Açai", "Dindin"],
        "verificado": true,
        "assinante": false,
    },{
        "condominio": "nautilus",
        "nome": "Erica Gress",
        "empresa": "Boteco de Gress",
        "profissao": "",
        "produtos": ["Cervejas", "Refrigerantes", "Bebidas"],
        "whatsapp": 5584999823910,
        "facebook": "",
        "instagram": "",
        "bloco": 0,
        "apt": 0,
        "pagamento": ["dinheiro", "Cartões"],
        "categoria": "Loja",
        "tags": ["Bebidas", "Restaurantes"],
        "verificado": true,
        "assinante": false,
    },{
        "condominio": "nautilus",
        "nome": "Jessica Melo",
        "empresa": "Budino Pudim",
        "profissao": "",
        "produtos": ["Pudim"],
        "whatsapp": 5584999028334,
        "facebook": "",
        "instagram": "",
        "bloco": 0,
        "apt": 0,
        "pagamento": ["dinheiro", "Cartões"],
        "categoria": "Loja",
        "tags": ["Pudim", "Restaurantes"],
        "verificado": true,
        "assinante": false,
    },{
        "condominio": "nautilus",
        "nome": "Adeilma",
        "empresa": "Dê Delicia",
        "profissao": "",
        "produtos": ["Bolos", "Sobremesas"],
        "whatsapp": 5584999606044,
        "facebook": "",
        "instagram": "",
        "bloco": 0,
        "apt": 0,
        "pagamento": ["dinheiro", "Cartões"],
        "categoria": "Loja",
        "tags": ["Bolos", "Restaurantes", "Sobremesas"],
        "verificado": true,
        "assinante": false,
    },{
        "condominio": "nautilus",
        "nome": "Edna",
        "empresa": "Edna",
        "profissao": "",
        "produtos": ["Bolos", "Sopa", "Canjica"],
        "whatsapp": 5584987071339,
        "facebook": "",
        "instagram": "",
        "bloco": 0,
        "apt": 0,
        "pagamento": ["dinheiro", "Cartões"],
        "categoria": "Loja",
        "tags": ["Bolos", "Restaurantes", "Sopas", "Canjica"],
        "verificado": true,
        "assinante": false,
    },{
        "condominio": "nautilus",
        "nome": "Fernando",
        "empresa": "Yakysoba do Fernando",
        "profissao": "",
        "produtos": ["Yakysoba"],
        "whatsapp": 5584998649440,
        "facebook": "",
        "instagram": "",
        "bloco": 0,
        "apt": 0,
        "pagamento": ["dinheiro", "Cartões"],
        "categoria": "Loja",
        "tags": ["Restaurantes", "Yakysoba"],
        "verificado": true,
        "assinante": false,
    },{
        "condominio": "nautilus",
        "nome": "Netinha Meira",
        "empresa": "Netinha Sobremesas",
        "profissao": "",
        "produtos": ["Bolos", "Dindin Gourmet"],
        "whatsapp": 5584999776490,
        "facebook": "",
        "instagram": "",
        "bloco": 0,
        "apt": 0,
        "pagamento": ["dinheiro", "Cartões"],
        "categoria": "Loja",
        "tags": ["Restaurantes", "Dindin", "Bolos"],
        "verificado": true,
        "assinante": false,
    }

]
